### ISSUE TITLE
Breaking typo in tests + dereferencing null pointer error.

### ISSUE THREAD

**Issue by iago-lito** [computations/lagrange-ng#3]
Hi, and thank you for this rewriting of Lagrange :)

I have downloaded the project, but the tests do not pass on my machine:
-  The first failure seems to be a simple mistake that the `lagrange_mode::OPTIMIZE` identifier had not been correctly renamed to `lagrange_operation_mode::OPTIMIZE` within `tests/src/context.cpp`.
- But the second failure seems more engaged, as it involves null pointer dereferencing:

```sh
$ uname -a
Linux etak 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64 GNU/Linux
$ git clone --recursive --depth 1 git@github.com:computations/lagrange-ng.git
$ cd lagrange-ng
$ sed -i 's/lagrange_mode::OPTIMIZE/lagrange_operation_mode::OPTIMIZE/g' tests/src/context.cpp
$ make tests
# ... <compilation succeeds, then..>
./bin/lagrange-test
[==========] Running 46 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 25 tests from TreeReader
[ RUN      ] TreeReader.simple0
[       OK ] TreeReader.simple0 (0 ms)
[ RUN      ] TreeReader.simple1
[       OK ] TreeReader.simple1 (0 ms)
[ RUN      ] TreeReader.simple2
[       OK ] TreeReader.simple2 (0 ms)
[ RUN      ] TreeReader.simple3
[       OK ] TreeReader.simple3 (0 ms)
[ RUN      ] TreeReader.simple4
[       OK ] TreeReader.simple4 (0 ms)
[ RUN      ] TreeReader.simple5
[       OK ] TreeReader.simple5 (0 ms)
[ RUN      ] TreeReader.simple6
[       OK ] TreeReader.simple6 (0 ms)
[ RUN      ] TreeReader.simple7
[       OK ] TreeReader.simple7 (0 ms)
[ RUN      ] TreeReader.simple8
[       OK ] TreeReader.simple8 (0 ms)
[ RUN      ] TreeReader.simple9
[       OK ] TreeReader.simple9 (0 ms)
[ RUN      ] TreeReader.simple10
[       OK ] TreeReader.simple10 (0 ms)
[ RUN      ] TreeReader.simple11
[       OK ] TreeReader.simple11 (0 ms)
[ RUN      ] TreeReader.badtrees1
[       OK ] TreeReader.badtrees1 (0 ms)
[ RUN      ] TreeReader.badtrees2
[       OK ] TreeReader.badtrees2 (0 ms)
[ RUN      ] TreeReader.badtrees3
[       OK ] TreeReader.badtrees3 (0 ms)
[ RUN      ] TreeReader.badtrees4
[       OK ] TreeReader.badtrees4 (0 ms)
[ RUN      ] TreeReader.badtrees5
[       OK ] TreeReader.badtrees5 (0 ms)
[ RUN      ] TreeReader.badtrees6
[       OK ] TreeReader.badtrees6 (0 ms)
[ RUN      ] TreeReader.badtrees7
[       OK ] TreeReader.badtrees7 (0 ms)
[ RUN      ] TreeReader.badtrees8
[       OK ] TreeReader.badtrees8 (0 ms)
[ RUN      ] TreeReader.badtrees9
[       OK ] TreeReader.badtrees9 (0 ms)
[ RUN      ] TreeReader.badtrees10
[       OK ] TreeReader.badtrees10 (0 ms)
[ RUN      ] TreeReader.badtrees11
[       OK ] TreeReader.badtrees11 (0 ms)
[ RUN      ] TreeReader.manytrees
[       OK ] TreeReader.manytrees (390 ms)
[ DISABLED ] TreeReader.DISABLED_pathologic0
[ RUN      ] TreeReader.SlothsTree
[       OK ] TreeReader.SlothsTree (0 ms)
[----------] 25 tests from TreeReader (392 ms total)

[----------] 4 tests from Workspace
[ RUN      ] Workspace.simple0
[       OK ] Workspace.simple0 (0 ms)
[ RUN      ] Workspace.simple1
[       OK ] Workspace.simple1 (0 ms)
[ RUN      ] Workspace.minsize
[       OK ] Workspace.minsize (0 ms)
[ RUN      ] Workspace.maxareas
[       OK ] Workspace.maxareas (0 ms)
[----------] 4 tests from Workspace (0 ms total)

[----------] 9 tests from OperationTest
[ RUN      ] OperationTest.ExpmSimple0
[       OK ] OperationTest.ExpmSimple0 (1 ms)
[ RUN      ] OperationTest.ExpmSimple1
[       OK ] OperationTest.ExpmSimple1 (0 ms)
[ RUN      ] OperationTest.DispersionSimple0
AddressSanitizer:DEADLYSIGNAL
=================================================================
==754029==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000069 (pc 0x56292f687233 bp 0x6110038945a8 sp 0x7ffe98880d90 T0)
==754029==The signal is caused by a READ memory access.
==754029==Hint: address points to the zero page.
    #0 0x56292f687233 in DispersionOperation::eval(std::shared_ptr<Workspace> const&) (/home/iago-lito/Downloads/lagrange-ng/bin/lagrange-test+0xa3233)
    #1 0x56292f64add0 in OperationTest_DispersionSimple0_Test::TestBody() /home/iago-lito/Downloads/lagrange-ng/tests/src/operation.cpp:210
    #2 0x7f00aaf3c40c in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x6240c)
    #3 0x7f00aaf293fd in testing::Test::Run() (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x4f3fd)
    #4 0x7f00aaf295b4 in testing::TestInfo::Run() (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x4f5b4)
    #5 0x7f00aaf296d4 in testing::TestSuite::Run() (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x4f6d4)
    #6 0x7f00aaf3160b in testing::internal::UnitTestImpl::RunAllTests() (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x5760b)
    #7 0x7f00aaf298a3 in testing::UnitTest::Run() (/home/iago-lito/Downloads/lagrange-ng/build/lib/libgtest.so.1.13.0+0x4f8a3)
    #8 0x56292f66e372 in RUN_ALL_TESTS() /home/iago-lito/Downloads/lagrange-ng/build/tests/googletest-src/googletest/include/gtest/gtest.h:2314
    #9 0x56292f66e191 in main /home/iago-lito/Downloads/lagrange-ng/tests/src/main.cpp:10
    #10 0x7f00aa15478f  (/usr/lib/libc.so.6+0x2378f)
    #11 0x7f00aa154849 in __libc_start_main (/usr/lib/libc.so.6+0x23849)
    #12 0x56292f6007e4 in _start (/home/iago-lito/Downloads/lagrange-ng/bin/lagrange-test+0x1c7e4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/iago-lito/Downloads/lagrange-ng/bin/lagrange-test+0xa3233) in DispersionOperation::eval(std::shared_ptr<Workspace> const&)
==754029==ABORTING
make: *** [makefile:13: tests] Error 1 
```

Is this an easy fix? Do the tests pass on your machines? If yes, would it be an architecture-related problem?

**Comment by computations** [comment]
Thanks for pointing this out. You are correct that the first problem is a simple refactor error. Fortunately, the second error is also refactor error. I have corrected both and pushed and update. Let me know if everything is working on your end.

**Comment by iago-lito** [comment]
Great, thank you for the fix and the reactiveness :)
